from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

import threading
import time

#Account in all the regions is analyticsdata@getairmail.com / Analyze@1234
# def walk_dog():
#     time.sleep(8)
#     print("You finish walk the doog")
#
#
# def take_out_thrash():
#     time.sleep(2)
#     print("take out trash")
#
#
# def get_mail():
#     time.sleep(4)
#     print("you get the mail")


# chore1 = threading.Thread(target=walk_dog)
# chore1.start()
#
# chore2 = threading.Thread(target=take_out_thrash)
# chore2.start()
#
# chore3 = threading.Thread(target=get_mail)
# chore3.start()


# def create_Headless():
#     chrome_options = Options()
#     chrome_options.add_argument("--headless=new")  # Use the new headless mode
#     chrome_options.add_argument("--no-sandbox")  # required for running as root
#     chrome_options.add_argument("--disable-dev-shm-usage")  # overcome limited resource problems
#     driver = webdriver.Chrome(options=chrome_options)
#     return driver



def ubstagingwebsdk():
    #driver = create_Headless()
    #driver = create_headless_driver()
    url1 = 'https://staging-bots.korebots.com/webclient/67f62984207a4363b1d1fa90e180ec2ef269be8cf44a4e5e8ce73c3f8cbefd5bst4d'
    #url1= 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    driver = webdriver.Chrome()
    driver.get(url1)
    time.sleep(9)
    InputBox = driver.find_element(By.CSS_SELECTOR, '[placeholder="Message..."]')
    time.sleep(9)
    InputBox.send_keys("Cheat lang en", Keys.ENTER)
    time.sleep(9)
    InputBox.send_keys("Hi", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Message Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(5)
    # assert 'This message is from content variables'
    InputBox.send_keys("Dialog Service Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Script Node", Keys.ENTER)
    time.sleep(3)
    # How do I terminate savings bank account?
    InputBox.send_keys("How do I terminate savings bank account?", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Hello", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 0-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("0", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 4-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("4", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 9-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("9", Keys.ENTER)
    time.sleep(5)
    # CSAT - highly unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly unsatisfied", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    # CSAT - unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("unsatisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT-Average
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Average", Keys.ENTER)
    time.sleep(5)

    # CSAT-Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Satisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT- Highly Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly Satisfied", Keys.ENTER)
    time.sleep(5)

    # LikeDislike-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely Likely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely UnLikely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python like dislike", Keys.ENTER)
    time.sleep(5)

    # EntityNodeConnectionsValidation -Entity
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("AttachmentEntityValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    print('UB Staging websdk interaction is completed.')



def appstagingwebsdk():
    url33='https://staging-xo.korebots.com/xo-webclient/273f5bd35ae342f79475875a1606f251f7e38680e97d437aaf148bfa04297773sta5?lang'
    #url33 = 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    driver=webdriver.Chrome()
    driver.get(url33)

    time.sleep(9)
    InputBox = driver.find_element(By.CSS_SELECTOR, '[placeholder="Type a message"]')
    time.sleep(9)
    InputBox.send_keys("Cheat lang en", Keys.ENTER)
    time.sleep(9)
    InputBox.send_keys("Hi", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Message Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(5)
    # assert 'This message is from content variables'
    InputBox.send_keys("Dialog Service Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Script Node", Keys.ENTER)
    time.sleep(3)
    # How do I terminate savings bank account?
    InputBox.send_keys("How do I terminate savings bank account?", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Hello", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 0-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("0", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 4-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("4", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 9-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("9", Keys.ENTER)
    time.sleep(5)
    # CSAT - highly unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly unsatisfied", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    # CSAT - unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("unsatisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT-Average
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Average", Keys.ENTER)
    time.sleep(5)

    # CSAT-Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Satisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT- Highly Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly Satisfied", Keys.ENTER)
    time.sleep(5)

    # LikeDislike-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely Likely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely UnLikely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python like dislike", Keys.ENTER)
    time.sleep(5)

    # EntityNodeConnectionsValidation -Entity
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("AttachmentEntityValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    print('Standard app Staging websdk interaction is completed.')

def standardbotstagingwebsdk():
    url2 = 'https://staging-bots.korebots.com/webclient/dd13d41ba27b4ac69461abb60ac8f831f4cb04a466c4469cb4d50316a8b199a5steb'
    #url2 = 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    driver = webdriver.Chrome()
    driver.get(url2)
    time.sleep(9)
    InputBox = driver.find_element(By.CSS_SELECTOR, '[placeholder="Message..."]')
    time.sleep(9)
    InputBox.send_keys("Cheat lang en", Keys.ENTER)
    time.sleep(9)
    InputBox.send_keys("Hi", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Message Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(5)
    # assert 'This message is from content variables'
    InputBox.send_keys("Dialog Service Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Script Node", Keys.ENTER)
    time.sleep(3)
    # How do I terminate savings bank account?
    InputBox.send_keys("How do I terminate savings bank account?", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Hello", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 0-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("0", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 4-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("4", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 9-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("9", Keys.ENTER)
    time.sleep(5)
    # CSAT - highly unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly unsatisfied", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    # CSAT - unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("unsatisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT-Average
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Average", Keys.ENTER)
    time.sleep(5)

    # CSAT-Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Satisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT- Highly Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly Satisfied", Keys.ENTER)
    time.sleep(5)

    # LikeDislike-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely Likely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely UnLikely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python like dislike", Keys.ENTER)
    time.sleep(5)

    # EntityNodeConnectionsValidation -Entity
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("AttachmentEntityValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    print('Standard bot Staging websdk interaction is completed.')


def standardbotprod():
    url3 = 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    #url3 = 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    driver = webdriver.Chrome()
    driver.get(url3)
    time.sleep(9)
    InputBox = driver.find_element(By.CSS_SELECTOR, '[placeholder="Message..."]')
    time.sleep(9)
    InputBox.send_keys("Cheat lang en", Keys.ENTER)
    time.sleep(9)
    InputBox.send_keys("Hi", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Message Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(5)
    # assert 'This message is from content variables'
    InputBox.send_keys("Dialog Service Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Script Node", Keys.ENTER)
    time.sleep(3)
    # How do I terminate savings bank account?
    InputBox.send_keys("How do I terminate savings bank account?", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Hello", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 0-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("0", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 4-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("4", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 9-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("9", Keys.ENTER)
    time.sleep(5)
    # CSAT - highly unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly unsatisfied", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    # CSAT - unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("unsatisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT-Average
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Average", Keys.ENTER)
    time.sleep(5)

    # CSAT-Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Satisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT- Highly Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly Satisfied", Keys.ENTER)
    time.sleep(5)

    # LikeDislike-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely Likely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely UnLikely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python like dislike", Keys.ENTER)
    time.sleep(5)

    # EntityNodeConnectionsValidation -Entity
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("AttachmentEntityValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5);
    print('Standard bot prod  websdk interaction is completed.')


def ubprod():
    url4 = 'https://bots.kore.ai/webclient/a66f435413974eeaa1a78d0eaefae9a0768e89bf1eeb4304a46eb775b4f34668st3b'
    #url4= 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    driver = webdriver.Chrome()
    driver.get(url4)
    time.sleep(9)
    InputBox = driver.find_element(By.CSS_SELECTOR, '[placeholder="Message..."]')
    time.sleep(9)
    InputBox.send_keys("Cheat lang en", Keys.ENTER)
    time.sleep(9)
    InputBox.send_keys("Hi", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Message Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(5)
    # assert 'This message is from content variables'
    InputBox.send_keys("Dialog Service Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Script Node", Keys.ENTER)
    time.sleep(3)
    # How do I terminate savings bank account?
    InputBox.send_keys("How do I terminate savings bank account?", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Hello", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 0-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("0", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 4-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("4", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 9-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("9", Keys.ENTER)
    time.sleep(5)
    # CSAT - highly unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly unsatisfied", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    # CSAT - unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("unsatisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT-Average
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Average", Keys.ENTER)
    time.sleep(5)

    # CSAT-Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Satisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT- Highly Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly Satisfied", Keys.ENTER)
    time.sleep(5)

    # LikeDislike-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely Likely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely UnLikely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python like dislike", Keys.ENTER)
    time.sleep(5)

    # EntityNodeConnectionsValidation -Entity
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("AttachmentEntityValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    print('UB bot Prod websdk interaction is completed.')

def UxoProdApp():
    url45 = 'https://platform.kore.ai/xo-webclient/fe2adf4017cc4a66a4af0aba0c4a16550ca0194f30b64722835cd2053151df32st90?lang'
    #url45 = 'https://bots.kore.ai/webclient/0e07366caf994328be0a427c50c44904934e96923c2b4f428c927a3d217a9799st87'
    driver = webdriver.Chrome()
    driver.get(url45)
    time.sleep(9)
    InputBox = driver.find_element(By.CSS_SELECTOR, '[placeholder="Type a message"]')
    time.sleep(9)
    InputBox.send_keys("Cheat lang en", Keys.ENTER)
    time.sleep(9)
    InputBox.send_keys("Hi", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Message Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(5)
    # assert 'This message is from content variables'
    InputBox.send_keys("Dialog Service Node", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ContentVariableValidation", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Dialog Script Node", Keys.ENTER)
    time.sleep(3)
    # How do I terminate savings bank account?
    InputBox.send_keys("How do I terminate savings bank account?", Keys.ENTER)
    time.sleep(3)
    InputBox.send_keys("Hello", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("ValidationOfMultiplePromptsForEntityNode", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Delhi", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("3", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 0-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("0", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 4-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("4", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python selenium bad feedback survey", Keys.ENTER)
    time.sleep(5)
    # NPS Survey 9-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("NPSSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("9", Keys.ENTER)
    time.sleep(5)
    # CSAT - highly unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly unsatisfied", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    # CSAT - unsatisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("unsatisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT-Average
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Average", Keys.ENTER)
    time.sleep(5)

    # CSAT-Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Satisfied", Keys.ENTER)
    time.sleep(5)
    # CSAT- Highly Satisfied
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("CSATSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Highly Satisfied", Keys.ENTER)
    time.sleep(5)

    # LikeDislike-
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely Likely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("LikeDislikeSurveyValidationDialog", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Extremely UnLikely", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Python like dislike", Keys.ENTER)
    time.sleep(5)

    # EntityNodeConnectionsValidation -Entity
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)

    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("1", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("cheat lang en", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("EntityNodeConnectionsValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Entity", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("Greater Than", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("5", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("KoreDebuggerValidation", Keys.ENTER)
    time.sleep(7)
    InputBox.send_keys("AttachmentEntityValidation", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    InputBox.send_keys("test", Keys.ENTER)
    time.sleep(5)
    print('APP bot UXOProd websdk interaction is completed.')

stagingw = threading.Thread(target=ubstagingwebsdk)
stagingw.start()

standardbotstagingr = threading.Thread(target=standardbotstagingwebsdk)
standardbotstagingr.start()

standardbotprod = threading.Thread(target=standardbotprod)
standardbotprod.start()

ubprod = threading.Thread(target=ubprod)
ubprod.start()

uxoappstaging=threading.Thread(target=appstagingwebsdk)
uxoappstaging.start()

UUxoProdApp=threading.Thread(target=UxoProdApp)
UUxoProdApp.start()


stagingw.join()
UUxoProdApp.join()
standardbotstagingr.join()
standardbotprod.join()
ubprod.join()
uxoappstaging.join()